# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_ex', '0002_auto_20160819_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('friend_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
    ]
