# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_ex', '0006_auto_20160822_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belt_ex.User'),
        ),
    ]
